#include "Scene/StartScene.h"
#include "Scene/MapScene.h"
#include "Scene/SettingScene.h"
#include "Common/CommonMethod.h"
#include <algorithm>

USING_NS_CC;

MapScene *MapScene::createScene()
{
	return MapScene::create();
}

bool MapScene::init()
{

	if (!Scene::init())
	{
		return false;
	}

	MenuItemFont::setFontName("华文琥珀");
	MenuItemFont::setFontSize(40);

	if (!MapScene::panelInit())
	{
		return false;
	}
	if (!MapScene::mapInit())
	{
		return false;
	}
	if (!MapScene::landInit())
	{
		return false;
	}
	if (!MapScene::rollMap())
	{
		return false;
	}

	/*//测试
	log("test %f %f", pos_[2].x, pos_[2].y);
	auto sp = Sprite::create("hotel2.png");
	map_->addChild(sp, 5);
	sp->setAnchorPoint(Vec2(0.5, 0));
	sp->setPosition(pos_[11].x, pos_[11].y+32);
	*/
	return true;
}

//地图初始化
bool MapScene::mapInit()
{
	auto visible_size = Director::getInstance()->getVisibleSize();
	auto origin = Director::getInstance()->getVisibleOrigin();
	map_ = TMXTiledMap::create("map.tmx");
	assert(map_);
	map_->setAnchorPoint(Vec2::ZERO);
	perspectiveJump(45.f * 32.f, 18.f * 32.f);
	map_->getLayer("grass")->setLocalZOrder(-10);
	map_->getLayer("lake")->setLocalZOrder(-8);
	map_->getLayer("road")->setLocalZOrder(-6);
	map_->getLayer("land")->setLocalZOrder(-4);
	map_->getLayer("house")->setVisible(false);

	//测试
	auto listener = EventListenerTouchOneByOne::create();
	listener->onTouchBegan = [=](Touch *touch, Event *event) {
		auto touch_pos = touch->getLocation() - event->getCurrentTarget()->getPosition();
		auto tile_size = map_->getTileSize();
		auto map_size = map_->getMapSize();
		//log("visible_size:%.2f,%.2f", visible_size.width, visible_size.height);
		//log("tile_size:%.2f,%.2f", tile_size.width, tile_size.height);
		//log("map_size:%.2f,%.2f", map_size.width, map_size.height);
		auto x = static_cast<float>(static_cast<int>(touch_pos.x / tile_size.width));
		auto y = static_cast<float>(static_cast<int>(touch_pos.y / tile_size.height));
		//log("touched tile position to tiles in tilemap direction is x:%f,y:%f", x, y);
		return true;
	};
	map_->getEventDispatcher()->addEventListenerWithSceneGraphPriority(listener, map_);

	this->addChild(map_, -20, "map_");
	return true;
}

//添加地图滚动的监听和回调方法
bool MapScene::rollMap()
{
	auto visible_size = Director::getInstance()->getVisibleSize();
	auto origin = Director::getInstance()->getVisibleOrigin();
	auto map_size = map_->getMapSize();
	auto tile_size = map_->getTileSize();
	auto listener = EventListenerTouchOneByOne::create();
	static Vec2 start_pos(0, 0);
	listener->onTouchBegan = [=](Touch *touch, Event *event) {
		start_pos = touch->getLocation() - event->getCurrentTarget()->getPosition();
		return true;
	};
	listener->onTouchMoved = [=](Touch *touch, Event *event) {
		auto delta = touch->getLocation() - start_pos;
		auto x = std::min(0.0f, delta.x);
		x = std::max(x, visible_size.width - map_size.width * tile_size.width);
		auto y = std::min(0.0f, delta.y);
		y = std::max(y, visible_size.height - map_size.height * tile_size.height);
		event->getCurrentTarget()->setPosition(x, y);
		//log("your present touching position to the screen in GL direction is x:%.2f y:%.2f", finish_pos.x, finish_pos.y);
		//log("map position to the parent in GL direction change to x:%.2f y:%.2f", delta.x, delta.y);
	};
	map_->getEventDispatcher()->addEventListenerWithSceneGraphPriority(listener, map_);
	return true;
}

//初始化地图旁边的操作面板
bool MapScene::panelInit()
{
	auto visible_size = Director::getInstance()->getVisibleSize();
	Vec2 origin = Director::getInstance()->getVisibleOrigin();

	//面板初始化
	this->panel_ = Layer::create();
	panel_->setAnchorPoint(Vec2(0, 0));
	panel_->setPosition(Vec2::ZERO);
	this->addChild(panel_, 10);

	//向这个成员变量中添加按钮
	menu_item_.insert("close", MenuItemFont::create(ZH(" 退出 ")));
	menu_item_.insert("setting", MenuItemFont::create(ZH(" 设置 ")));
	menu_item_.insert("item", MenuItemFont::create(ZH(" 道具 ")));
	menu_item_.insert("stock", MenuItemFont::create(ZH(" 股市 ")));

	//从这个变量获取按钮项
	auto close_item = menu_item_.at("close");
	auto setting_item = menu_item_.at("setting");
	auto item_item = menu_item_.at("item");
	auto stock_item = menu_item_.at("stock");

	//按钮排列
	auto menu = Menu::create();
	menu->addChild(item_item, 30);
	menu->addChild(close_item, 30);
	menu->addChild(setting_item, 30);
	menu->addChild(stock_item, 30);
	menu->setPosition(Vec2(visible_size.width * 2 / 5, visible_size.height * 19 / 20));
	panel_->addChild(menu, 20);

	menu->alignItemsHorizontally();

	//更改按钮回调的执行
	close_item->setCallback([=](Ref *render) {
		auto scene = StartScene::createScene();
		Director::getInstance()->replaceScene(TransitionFade::create(0.5f, scene, Color3B(0, 255, 255)));
	});

	setting_item->setCallback([=](Ref *render) {
		auto scene = SettingScene::createScene();
		Director::getInstance()->pushScene(scene);
	});

	return true;
}

//将视角跳转到以地图上某个像素坐标为中心的相应位置
bool MapScene::perspectiveJump(float x, float y)
{
	auto visible_size = Director::getInstance()->getVisibleSize();
	auto map_size = map_->getMapSize();
	auto tile_size = map_->getTileSize();

	x = visible_size.width / 2.f - x;
	y = visible_size.height / 2.f - y;

	x = std::min(0.0f, x);
	x = std::max(x, visible_size.width - map_size.width * tile_size.width);
	y = std::min(0.0f, y);
	y = std::max(y, visible_size.height - map_size.height * tile_size.height);

	map_->setPosition(x, y);
	return true;
}

//添加地图上道路中心位置相对于地图右下角锚点的GL方向以像素为单位的坐标位置
bool MapScene::landInit()
{
	auto tile_size = map_->getTileSize();
	auto map_size = map_->getMapSize();
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), map_size.height * tile_size.height - tile_size.height * static_cast<float>(84)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), map_size.height * tile_size.height - tile_size.height * static_cast<float>(86)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), map_size.height * tile_size.height - tile_size.height * static_cast<float>(90)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), map_size.height * tile_size.height - tile_size.height * static_cast<float>(90)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), map_size.height * tile_size.height - tile_size.height * static_cast<float>(90)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), map_size.height * tile_size.height - tile_size.height * static_cast<float>(90)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(56), map_size.height * tile_size.height - tile_size.height * static_cast<float>(90)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), map_size.height * tile_size.height - tile_size.height * static_cast<float>(90)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), map_size.height * tile_size.height - tile_size.height * static_cast<float>(90)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), map_size.height * tile_size.height - tile_size.height * static_cast<float>(90)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), map_size.height * tile_size.height - tile_size.height * static_cast<float>(90)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(9);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), map_size.height * tile_size.height - tile_size.height * static_cast<float>(86)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), map_size.height * tile_size.height - tile_size.height * static_cast<float>(86)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(72), map_size.height * tile_size.height - tile_size.height * static_cast<float>(86)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), map_size.height * tile_size.height - tile_size.height * static_cast<float>(86)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), map_size.height * tile_size.height - tile_size.height * static_cast<float>(86)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), map_size.height * tile_size.height - tile_size.height * static_cast<float>(86)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), map_size.height * tile_size.height - tile_size.height * static_cast<float>(86)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), map_size.height * tile_size.height - tile_size.height * static_cast<float>(86)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), map_size.height * tile_size.height - tile_size.height * static_cast<float>(86)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), map_size.height * tile_size.height - tile_size.height * static_cast<float>(86)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(86)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(84)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(80)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), map_size.height * tile_size.height - tile_size.height * static_cast<float>(80)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), map_size.height * tile_size.height - tile_size.height * static_cast<float>(80)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), map_size.height * tile_size.height - tile_size.height * static_cast<float>(80)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), map_size.height * tile_size.height - tile_size.height * static_cast<float>(80)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), map_size.height * tile_size.height - tile_size.height * static_cast<float>(80)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), map_size.height * tile_size.height - tile_size.height * static_cast<float>(80)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), map_size.height * tile_size.height - tile_size.height * static_cast<float>(80)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(72), map_size.height * tile_size.height - tile_size.height * static_cast<float>(80)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), map_size.height * tile_size.height - tile_size.height * static_cast<float>(80)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), map_size.height * tile_size.height - tile_size.height * static_cast<float>(80)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), map_size.height * tile_size.height - tile_size.height * static_cast<float>(78)));
	type_.push_back(16);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), map_size.height * tile_size.height - tile_size.height * static_cast<float>(78)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), map_size.height * tile_size.height - tile_size.height * static_cast<float>(78)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), map_size.height * tile_size.height - tile_size.height * static_cast<float>(74)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), map_size.height * tile_size.height - tile_size.height * static_cast<float>(72)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(72), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), map_size.height * tile_size.height - tile_size.height * static_cast<float>(72)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), map_size.height * tile_size.height - tile_size.height * static_cast<float>(74)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), map_size.height * tile_size.height - tile_size.height * static_cast<float>(74)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), map_size.height * tile_size.height - tile_size.height * static_cast<float>(74)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), map_size.height * tile_size.height - tile_size.height * static_cast<float>(74)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), map_size.height * tile_size.height - tile_size.height * static_cast<float>(74)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), map_size.height * tile_size.height - tile_size.height * static_cast<float>(74)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), map_size.height * tile_size.height - tile_size.height * static_cast<float>(74)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(74)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(72)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(68)));
	type_.push_back(11);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), map_size.height * tile_size.height - tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), map_size.height * tile_size.height - tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), map_size.height * tile_size.height - tile_size.height * static_cast<float>(68)));
	type_.push_back(13);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), map_size.height * tile_size.height - tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), map_size.height * tile_size.height - tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), map_size.height * tile_size.height - tile_size.height * static_cast<float>(66)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(72), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(56), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), map_size.height * tile_size.height - tile_size.height * static_cast<float>(66)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), map_size.height * tile_size.height - tile_size.height * static_cast<float>(66)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), map_size.height * tile_size.height - tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), map_size.height * tile_size.height - tile_size.height * static_cast<float>(68)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(11);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), map_size.height * tile_size.height - tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), map_size.height * tile_size.height - tile_size.height * static_cast<float>(66)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), map_size.height * tile_size.height - tile_size.height * static_cast<float>(62)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(62)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(60)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(58)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(56)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), map_size.height * tile_size.height - tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), map_size.height * tile_size.height - tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), map_size.height * tile_size.height - tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), map_size.height * tile_size.height - tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), map_size.height * tile_size.height - tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), map_size.height * tile_size.height - tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), map_size.height * tile_size.height - tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), map_size.height * tile_size.height - tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), map_size.height * tile_size.height - tile_size.height * static_cast<float>(52)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), map_size.height * tile_size.height - tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), map_size.height * tile_size.height - tile_size.height * static_cast<float>(44)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(15);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(40)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(38)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(36)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(34)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(32)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), map_size.height * tile_size.height - tile_size.height * static_cast<float>(32)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), map_size.height * tile_size.height - tile_size.height * static_cast<float>(34)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), map_size.height * tile_size.height - tile_size.height * static_cast<float>(36)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), map_size.height * tile_size.height - tile_size.height * static_cast<float>(36)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), map_size.height * tile_size.height - tile_size.height * static_cast<float>(36)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), map_size.height * tile_size.height - tile_size.height * static_cast<float>(36)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), map_size.height * tile_size.height - tile_size.height * static_cast<float>(36)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), map_size.height * tile_size.height - tile_size.height * static_cast<float>(38)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), map_size.height * tile_size.height - tile_size.height * static_cast<float>(40)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(56), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), map_size.height * tile_size.height - tile_size.height * static_cast<float>(40)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), map_size.height * tile_size.height - tile_size.height * static_cast<float>(38)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), map_size.height * tile_size.height - tile_size.height * static_cast<float>(36)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), map_size.height * tile_size.height - tile_size.height * static_cast<float>(36)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), map_size.height * tile_size.height - tile_size.height * static_cast<float>(36)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), map_size.height * tile_size.height - tile_size.height * static_cast<float>(34)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), map_size.height * tile_size.height - tile_size.height * static_cast<float>(32)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), map_size.height * tile_size.height - tile_size.height * static_cast<float>(32)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), map_size.height * tile_size.height - tile_size.height * static_cast<float>(34)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), map_size.height * tile_size.height - tile_size.height * static_cast<float>(36)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), map_size.height * tile_size.height - tile_size.height * static_cast<float>(36)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), map_size.height * tile_size.height - tile_size.height * static_cast<float>(36)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), map_size.height * tile_size.height - tile_size.height * static_cast<float>(38)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), map_size.height * tile_size.height - tile_size.height * static_cast<float>(40)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), map_size.height * tile_size.height - tile_size.height * static_cast<float>(44)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), map_size.height * tile_size.height - tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), map_size.height * tile_size.height - tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), map_size.height * tile_size.height - tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), map_size.height * tile_size.height - tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), map_size.height * tile_size.height - tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), map_size.height * tile_size.height - tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), map_size.height * tile_size.height - tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(72), map_size.height * tile_size.height - tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), map_size.height * tile_size.height - tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(44)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(11);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), map_size.height * tile_size.height - tile_size.height * static_cast<float>(40)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), map_size.height * tile_size.height - tile_size.height * static_cast<float>(38)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), map_size.height * tile_size.height - tile_size.height * static_cast<float>(36)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), map_size.height * tile_size.height - tile_size.height * static_cast<float>(34)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), map_size.height * tile_size.height - tile_size.height * static_cast<float>(34)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), map_size.height * tile_size.height - tile_size.height * static_cast<float>(34)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), map_size.height * tile_size.height - tile_size.height * static_cast<float>(34)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), map_size.height * tile_size.height - tile_size.height * static_cast<float>(34)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), map_size.height * tile_size.height - tile_size.height * static_cast<float>(34)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(34)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(32)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(28)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(26)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(24)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(22)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(72), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(72), map_size.height * tile_size.height - tile_size.height * static_cast<float>(18)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), map_size.height * tile_size.height - tile_size.height * static_cast<float>(18)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), map_size.height * tile_size.height - tile_size.height * static_cast<float>(18)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), map_size.height * tile_size.height - tile_size.height * static_cast<float>(18)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), map_size.height * tile_size.height - tile_size.height * static_cast<float>(18)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), map_size.height * tile_size.height - tile_size.height * static_cast<float>(18)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), map_size.height * tile_size.height - tile_size.height * static_cast<float>(18)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), map_size.height * tile_size.height - tile_size.height * static_cast<float>(18)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(56), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(14);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), map_size.height * tile_size.height - tile_size.height * static_cast<float>(18)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), map_size.height * tile_size.height - tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), map_size.height * tile_size.height - tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), map_size.height * tile_size.height - tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), map_size.height * tile_size.height - tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), map_size.height * tile_size.height - tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), map_size.height * tile_size.height - tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), map_size.height * tile_size.height - tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), map_size.height * tile_size.height - tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), map_size.height * tile_size.height - tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), map_size.height * tile_size.height - tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), map_size.height * tile_size.height - tile_size.height * static_cast<float>(16)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), map_size.height * tile_size.height - tile_size.height * static_cast<float>(16)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), map_size.height * tile_size.height - tile_size.height * static_cast<float>(16)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(16)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(18)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(20)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(22)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(24)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), map_size.height * tile_size.height - tile_size.height * static_cast<float>(24)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), map_size.height * tile_size.height - tile_size.height * static_cast<float>(26)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), map_size.height * tile_size.height - tile_size.height * static_cast<float>(26)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), map_size.height * tile_size.height - tile_size.height * static_cast<float>(26)));
	type_.push_back(16);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), map_size.height * tile_size.height - tile_size.height * static_cast<float>(26)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), map_size.height * tile_size.height - tile_size.height * static_cast<float>(26)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), map_size.height * tile_size.height - tile_size.height * static_cast<float>(26)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), map_size.height * tile_size.height - tile_size.height * static_cast<float>(26)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), map_size.height * tile_size.height - tile_size.height * static_cast<float>(26)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), map_size.height * tile_size.height - tile_size.height * static_cast<float>(26)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), map_size.height * tile_size.height - tile_size.height * static_cast<float>(26)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), map_size.height * tile_size.height - tile_size.height * static_cast<float>(28)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), map_size.height * tile_size.height - tile_size.height * static_cast<float>(30)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), map_size.height * tile_size.height - tile_size.height * static_cast<float>(32)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), map_size.height * tile_size.height - tile_size.height * static_cast<float>(32)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), map_size.height * tile_size.height - tile_size.height * static_cast<float>(32)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), map_size.height * tile_size.height - tile_size.height * static_cast<float>(32)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), map_size.height * tile_size.height - tile_size.height * static_cast<float>(32)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), map_size.height * tile_size.height - tile_size.height * static_cast<float>(32)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), map_size.height * tile_size.height - tile_size.height * static_cast<float>(32)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), map_size.height * tile_size.height - tile_size.height * static_cast<float>(32)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), map_size.height * tile_size.height - tile_size.height * static_cast<float>(32)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), map_size.height * tile_size.height - tile_size.height * static_cast<float>(32)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), map_size.height * tile_size.height - tile_size.height * static_cast<float>(34)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), map_size.height * tile_size.height - tile_size.height * static_cast<float>(36)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), map_size.height * tile_size.height - tile_size.height * static_cast<float>(38)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), map_size.height * tile_size.height - tile_size.height * static_cast<float>(38)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), map_size.height * tile_size.height - tile_size.height * static_cast<float>(38)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), map_size.height * tile_size.height - tile_size.height * static_cast<float>(38)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), map_size.height * tile_size.height - tile_size.height * static_cast<float>(38)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), map_size.height * tile_size.height - tile_size.height * static_cast<float>(38)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), map_size.height * tile_size.height - tile_size.height * static_cast<float>(38)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), map_size.height * tile_size.height - tile_size.height * static_cast<float>(40)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), map_size.height * tile_size.height - tile_size.height * static_cast<float>(40)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), map_size.height * tile_size.height - tile_size.height * static_cast<float>(42)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), map_size.height * tile_size.height - tile_size.height * static_cast<float>(44)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(46)));
	type_.push_back(16);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(48)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(52)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), map_size.height * tile_size.height - tile_size.height * static_cast<float>(52)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), map_size.height * tile_size.height - tile_size.height * static_cast<float>(52)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), map_size.height * tile_size.height - tile_size.height * static_cast<float>(52)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), map_size.height * tile_size.height - tile_size.height * static_cast<float>(52)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), map_size.height * tile_size.height - tile_size.height * static_cast<float>(52)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), map_size.height * tile_size.height - tile_size.height * static_cast<float>(52)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), map_size.height * tile_size.height - tile_size.height * static_cast<float>(52)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), map_size.height * tile_size.height - tile_size.height * static_cast<float>(52)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), map_size.height * tile_size.height - tile_size.height * static_cast<float>(52)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), map_size.height * tile_size.height - tile_size.height * static_cast<float>(52)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), map_size.height * tile_size.height - tile_size.height * static_cast<float>(52)));
	type_.push_back(11);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), map_size.height * tile_size.height - tile_size.height * static_cast<float>(52)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), map_size.height * tile_size.height - tile_size.height * static_cast<float>(54)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), map_size.height * tile_size.height - tile_size.height * static_cast<float>(56)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), map_size.height * tile_size.height - tile_size.height * static_cast<float>(58)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), map_size.height * tile_size.height - tile_size.height * static_cast<float>(58)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), map_size.height * tile_size.height - tile_size.height * static_cast<float>(58)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), map_size.height * tile_size.height - tile_size.height * static_cast<float>(58)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), map_size.height * tile_size.height - tile_size.height * static_cast<float>(58)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), map_size.height * tile_size.height - tile_size.height * static_cast<float>(58)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), map_size.height * tile_size.height - tile_size.height * static_cast<float>(58)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), map_size.height * tile_size.height - tile_size.height * static_cast<float>(58)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), map_size.height * tile_size.height - tile_size.height * static_cast<float>(60)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), map_size.height * tile_size.height - tile_size.height * static_cast<float>(62)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), map_size.height * tile_size.height - tile_size.height * static_cast<float>(64)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), map_size.height * tile_size.height - tile_size.height * static_cast<float>(66)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), map_size.height * tile_size.height - tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), map_size.height * tile_size.height - tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), map_size.height * tile_size.height - tile_size.height * static_cast<float>(68)));
	type_.push_back(12);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), map_size.height * tile_size.height - tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), map_size.height * tile_size.height - tile_size.height * static_cast<float>(68)));
	type_.push_back(11);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(70)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(72)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(74)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), map_size.height * tile_size.height - tile_size.height * static_cast<float>(74)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), map_size.height * tile_size.height - tile_size.height * static_cast<float>(74)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), map_size.height * tile_size.height - tile_size.height * static_cast<float>(78)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), map_size.height * tile_size.height - tile_size.height * static_cast<float>(80)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(15);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(84)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), map_size.height * tile_size.height - tile_size.height * static_cast<float>(86)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), map_size.height * tile_size.height - tile_size.height * static_cast<float>(86)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), map_size.height * tile_size.height - tile_size.height * static_cast<float>(88)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), map_size.height * tile_size.height - tile_size.height * static_cast<float>(86)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), map_size.height * tile_size.height - tile_size.height * static_cast<float>(84)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), map_size.height * tile_size.height - tile_size.height * static_cast<float>(80)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), map_size.height * tile_size.height - tile_size.height * static_cast<float>(78)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(56), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(10);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), map_size.height * tile_size.height - tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), map_size.height * tile_size.height - tile_size.height * static_cast<float>(78)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), map_size.height * tile_size.height - tile_size.height * static_cast<float>(80)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(56), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), map_size.height * tile_size.height - tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	return true;
}