#include "Scene/StartScene.h"
#include "Scene/MapScene.h"
#include "Scene/SettingScene.h"
#include "ZH.h"

USING_NS_CC;

MapScene *MapScene::createScene()
{
	return MapScene::create();
}

bool MapScene::init()
{

	if (!Scene::init())
	{
		return false;
	}

	MenuItemFont::setFontName("华文琥珀");
	MenuItemFont::setFontSize(20);

	if (!MapScene::panelInit())
	{
		return false;
	}
	if (!MapScene::mapInit())
	{
		return false;
	}
	if (!MapScene::landInit())
	{
		return false;
	}
	if (!MapScene::rollMap())
	{
		return false;
	}
	return true;

	log("test %f %f", pos_[2].x, pos_[2].y);

	return true;
}

//地图初始化
bool MapScene::mapInit()
{
	auto visibleSize = Director::getInstance()->getVisibleSize();
	Vec2 origin = Director::getInstance()->getVisibleOrigin();
	map_ = TMXTiledMap::create("map.tmx");
	assert(map_);
	map_->setAnchorPoint(Vec2::ANCHOR_TOP_LEFT);
	map_->setPosition(0, visibleSize.height);
	map_->getLayer("grass")->setLocalZOrder(-10);
	map_->getLayer("lake")->setLocalZOrder(-8);
	map_->getLayer("road")->setLocalZOrder(-6);
	map_->getLayer("land")->setLocalZOrder(-4);
	map_->getLayer("house")->setVisible(false);

	//测试
	auto listener = EventListenerTouchOneByOne::create();
	listener->onTouchBegan = [=](Touch *touch, Event *event) {
		auto touch_pos = touch->getLocation() - event->getCurrentTarget()->getPosition();
		auto tiledSize = map_->getTileSize();
		auto mapSize = map_->getMapSize();
		log("visibleSize:%.2f,%.2f", visibleSize.width, visibleSize.height);
		log("tiledSize:%.2f,%.2f", tiledSize.width, tiledSize.height);
		log("mapSize:%.2f,%.2f", mapSize.width, mapSize.height);
		auto x = static_cast<float>(static_cast<int>(touch_pos.x / tiledSize.width));
		auto y = static_cast<float>(static_cast<int>(touch_pos.y / tiledSize.height));
		log("touched tile position to tiles in tilemap direction is x:%d,y:%d", x, y);
		return true;
	};
	map_->getEventDispatcher()->addEventListenerWithSceneGraphPriority(listener, map_);

	this->addChild(map_, -20, "map");
	return true;
}

//添加地图滚动的监听和回调方法
bool MapScene::rollMap()
{
	auto listener = EventListenerTouchOneByOne::create();
	static Vec2 start_pos(0, 0);
	listener->onTouchBegan = [=](Touch *touch, Event *event) {
		auto target = event->getCurrentTarget();
		start_pos = touch->getLocation() - target->getPosition();

		return true;
	};
	listener->onTouchMoved = [=](Touch *touch, Event *event) {
		auto target = event->getCurrentTarget();
		auto finish_pos = touch->getLocation();
		auto delta = finish_pos - start_pos;
		target->setPosition(delta);
		//log("your present touching position to the screen in GL direction is x:%.2f y:%.2f", finish_pos.x, finish_pos.y);
		//log("map position to the parent in GL direction change to x:%.2f y:%.2f", delta.x, delta.y);
	};
	map_->getEventDispatcher()->addEventListenerWithSceneGraphPriority(listener, map_);
	return true;
}

//初始化地图旁边的操作面板
bool MapScene::panelInit()
{
	auto visibleSize = Director::getInstance()->getVisibleSize();
	Vec2 origin = Director::getInstance()->getVisibleOrigin();

	//面板初始化
	this->panel_ = Layer::create();
	panel_->setAnchorPoint(Vec2(0, 0));
	panel_->setPosition(Vec2::ZERO);
	this->addChild(panel_, 10);

	//向这个成员变量中添加按钮
	menu_item_.insert("close", MenuItemFont::create(ZH("退出")));
	menu_item_.insert("setting", MenuItemFont::create(ZH("设置")));
	menu_item_.insert("item", MenuItemFont::create(ZH("道具")));
	menu_item_.insert("stock", MenuItemFont::create(ZH("股市")));

	//从这个变量获取按钮项
	auto close_item = menu_item_.at("close");
	auto setting_item = menu_item_.at("setting");
	auto item_item = menu_item_.at("item");
	auto stock_item = menu_item_.at("stock");

	//按钮排列
	auto menu = Menu::create();
	menu->addChild(item_item, 30);
	menu->addChild(close_item, 30);
	menu->addChild(setting_item, 30);
	menu->addChild(stock_item, 30);
	menu->setPosition(Vec2(visibleSize.width * 2 / 5, visibleSize.height * 14 / 15));
	panel_->addChild(menu, 20);

	menu->alignItemsHorizontally();

	//更改按钮回调的执行
	close_item->setCallback([=](Ref *render) {
		auto scene = StartScene::createScene();
		Director::getInstance()->replaceScene(TransitionFade::create(0.5f, scene, Color3B(0, 255, 255)));
	});

	setting_item->setCallback([=](Ref *render) {
		auto scene = SettingScene::createScene();
		Director::getInstance()->pushScene(scene);
	});

	return true;
}

//添加地图上道路中心位置相对于地图锚点的GL像素坐标位置
bool MapScene::landInit()
{
	auto tile_size = map_->getTileSize();
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), -tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), -tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), -tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), -tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), -tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), -tile_size.height * static_cast<float>(82)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), -tile_size.height * static_cast<float>(84)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), -tile_size.height * static_cast<float>(86)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), -tile_size.height * static_cast<float>(88)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(88)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), -tile_size.height * static_cast<float>(88)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), -tile_size.height * static_cast<float>(88)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), -tile_size.height * static_cast<float>(88)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), -tile_size.height * static_cast<float>(88)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), -tile_size.height * static_cast<float>(88)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), -tile_size.height * static_cast<float>(90)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), -tile_size.height * static_cast<float>(90)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), -tile_size.height * static_cast<float>(90)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), -tile_size.height * static_cast<float>(90)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(56), -tile_size.height * static_cast<float>(90)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), -tile_size.height * static_cast<float>(90)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), -tile_size.height * static_cast<float>(90)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), -tile_size.height * static_cast<float>(90)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), -tile_size.height * static_cast<float>(90)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), -tile_size.height * static_cast<float>(88)));
	type_.push_back(9);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), -tile_size.height * static_cast<float>(88)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), -tile_size.height * static_cast<float>(88)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), -tile_size.height * static_cast<float>(86)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), -tile_size.height * static_cast<float>(86)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(72), -tile_size.height * static_cast<float>(86)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), -tile_size.height * static_cast<float>(86)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), -tile_size.height * static_cast<float>(86)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), -tile_size.height * static_cast<float>(86)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), -tile_size.height * static_cast<float>(86)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), -tile_size.height * static_cast<float>(86)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), -tile_size.height * static_cast<float>(86)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), -tile_size.height * static_cast<float>(86)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(86)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(84)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(80)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), -tile_size.height * static_cast<float>(80)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), -tile_size.height * static_cast<float>(80)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), -tile_size.height * static_cast<float>(80)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), -tile_size.height * static_cast<float>(80)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), -tile_size.height * static_cast<float>(80)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), -tile_size.height * static_cast<float>(80)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), -tile_size.height * static_cast<float>(80)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(72), -tile_size.height * static_cast<float>(80)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), -tile_size.height * static_cast<float>(80)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), -tile_size.height * static_cast<float>(80)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), -tile_size.height * static_cast<float>(78)));
	type_.push_back(16);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), -tile_size.height * static_cast<float>(78)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), -tile_size.height * static_cast<float>(78)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), -tile_size.height * static_cast<float>(76)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), -tile_size.height * static_cast<float>(74)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), -tile_size.height * static_cast<float>(72)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), -tile_size.height * static_cast<float>(70)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), -tile_size.height * static_cast<float>(70)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), -tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), -tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(72), -tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), -tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), -tile_size.height * static_cast<float>(72)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), -tile_size.height * static_cast<float>(74)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), -tile_size.height * static_cast<float>(74)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), -tile_size.height * static_cast<float>(74)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), -tile_size.height * static_cast<float>(74)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), -tile_size.height * static_cast<float>(74)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), -tile_size.height * static_cast<float>(74)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), -tile_size.height * static_cast<float>(74)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(74)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(72)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(70)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(68)));
	type_.push_back(11);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), -tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), -tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), -tile_size.height * static_cast<float>(68)));
	type_.push_back(13);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), -tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), -tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), -tile_size.height * static_cast<float>(66)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), -tile_size.height * static_cast<float>(64)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), -tile_size.height * static_cast<float>(64)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), -tile_size.height * static_cast<float>(64)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(72), -tile_size.height * static_cast<float>(64)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), -tile_size.height * static_cast<float>(64)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), -tile_size.height * static_cast<float>(64)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), -tile_size.height * static_cast<float>(64)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), -tile_size.height * static_cast<float>(64)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), -tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), -tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), -tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(56), -tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), -tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), -tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), -tile_size.height * static_cast<float>(64)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), -tile_size.height * static_cast<float>(66)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), -tile_size.height * static_cast<float>(66)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), -tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), -tile_size.height * static_cast<float>(68)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), -tile_size.height * static_cast<float>(70)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), -tile_size.height * static_cast<float>(70)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), -tile_size.height * static_cast<float>(70)));
	type_.push_back(11);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), -tile_size.height * static_cast<float>(70)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), -tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), -tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), -tile_size.height * static_cast<float>(70)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), -tile_size.height * static_cast<float>(70)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), -tile_size.height * static_cast<float>(70)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), -tile_size.height * static_cast<float>(70)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), -tile_size.height * static_cast<float>(70)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), -tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), -tile_size.height * static_cast<float>(66)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), -tile_size.height * static_cast<float>(64)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), -tile_size.height * static_cast<float>(64)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), -tile_size.height * static_cast<float>(64)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), -tile_size.height * static_cast<float>(64)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), -tile_size.height * static_cast<float>(64)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), -tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), -tile_size.height * static_cast<float>(64)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), -tile_size.height * static_cast<float>(62)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(62)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(60)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(58)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(56)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), -tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), -tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), -tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), -tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), -tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), -tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), -tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), -tile_size.height * static_cast<float>(54)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), -tile_size.height * static_cast<float>(52)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), -tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), -tile_size.height * static_cast<float>(48)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), -tile_size.height * static_cast<float>(48)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), -tile_size.height * static_cast<float>(48)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), -tile_size.height * static_cast<float>(48)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), -tile_size.height * static_cast<float>(48)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), -tile_size.height * static_cast<float>(48)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), -tile_size.height * static_cast<float>(46)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), -tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), -tile_size.height * static_cast<float>(44)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), -tile_size.height * static_cast<float>(42)));
	type_.push_back(15);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), -tile_size.height * static_cast<float>(42)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(42)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(40)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(38)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(36)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(34)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(32)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), -tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), -tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), -tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), -tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), -tile_size.height * static_cast<float>(30)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), -tile_size.height * static_cast<float>(30)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), -tile_size.height * static_cast<float>(30)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), -tile_size.height * static_cast<float>(30)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), -tile_size.height * static_cast<float>(32)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), -tile_size.height * static_cast<float>(34)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), -tile_size.height * static_cast<float>(36)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), -tile_size.height * static_cast<float>(36)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), -tile_size.height * static_cast<float>(36)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), -tile_size.height * static_cast<float>(36)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), -tile_size.height * static_cast<float>(36)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), -tile_size.height * static_cast<float>(38)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), -tile_size.height * static_cast<float>(40)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), -tile_size.height * static_cast<float>(42)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), -tile_size.height * static_cast<float>(42)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), -tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), -tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), -tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(56), -tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), -tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), -tile_size.height * static_cast<float>(42)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), -tile_size.height * static_cast<float>(42)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), -tile_size.height * static_cast<float>(40)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), -tile_size.height * static_cast<float>(38)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), -tile_size.height * static_cast<float>(36)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), -tile_size.height * static_cast<float>(36)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), -tile_size.height * static_cast<float>(36)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), -tile_size.height * static_cast<float>(34)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), -tile_size.height * static_cast<float>(32)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), -tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), -tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), -tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), -tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), -tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), -tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), -tile_size.height * static_cast<float>(30)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), -tile_size.height * static_cast<float>(32)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), -tile_size.height * static_cast<float>(34)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), -tile_size.height * static_cast<float>(36)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), -tile_size.height * static_cast<float>(36)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), -tile_size.height * static_cast<float>(36)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), -tile_size.height * static_cast<float>(38)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), -tile_size.height * static_cast<float>(40)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), -tile_size.height * static_cast<float>(42)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), -tile_size.height * static_cast<float>(42)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), -tile_size.height * static_cast<float>(42)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), -tile_size.height * static_cast<float>(44)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), -tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), -tile_size.height * static_cast<float>(46)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), -tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), -tile_size.height * static_cast<float>(46)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), -tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), -tile_size.height * static_cast<float>(46)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), -tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), -tile_size.height * static_cast<float>(48)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), -tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), -tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), -tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), -tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), -tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), -tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), -tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(72), -tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), -tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), -tile_size.height * static_cast<float>(48)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), -tile_size.height * static_cast<float>(48)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), -tile_size.height * static_cast<float>(48)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), -tile_size.height * static_cast<float>(48)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), -tile_size.height * static_cast<float>(48)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), -tile_size.height * static_cast<float>(48)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), -tile_size.height * static_cast<float>(48)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(48)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(44)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(42)));
	type_.push_back(11);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), -tile_size.height * static_cast<float>(42)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), -tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), -tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), -tile_size.height * static_cast<float>(42)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), -tile_size.height * static_cast<float>(42)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), -tile_size.height * static_cast<float>(42)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), -tile_size.height * static_cast<float>(40)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), -tile_size.height * static_cast<float>(38)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), -tile_size.height * static_cast<float>(36)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), -tile_size.height * static_cast<float>(34)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), -tile_size.height * static_cast<float>(34)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), -tile_size.height * static_cast<float>(34)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), -tile_size.height * static_cast<float>(34)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), -tile_size.height * static_cast<float>(34)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), -tile_size.height * static_cast<float>(34)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(34)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(32)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(30)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(28)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(26)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(24)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(22)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(88), -tile_size.height * static_cast<float>(20)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(86), -tile_size.height * static_cast<float>(20)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(84), -tile_size.height * static_cast<float>(20)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(82), -tile_size.height * static_cast<float>(20)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(80), -tile_size.height * static_cast<float>(20)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(78), -tile_size.height * static_cast<float>(20)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(76), -tile_size.height * static_cast<float>(20)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(74), -tile_size.height * static_cast<float>(20)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(72), -tile_size.height * static_cast<float>(20)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(72), -tile_size.height * static_cast<float>(18)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(70), -tile_size.height * static_cast<float>(18)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(68), -tile_size.height * static_cast<float>(18)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(66), -tile_size.height * static_cast<float>(18)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(64), -tile_size.height * static_cast<float>(18)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(62), -tile_size.height * static_cast<float>(18)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), -tile_size.height * static_cast<float>(18)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), -tile_size.height * static_cast<float>(18)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), -tile_size.height * static_cast<float>(20)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(56), -tile_size.height * static_cast<float>(20)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), -tile_size.height * static_cast<float>(20)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), -tile_size.height * static_cast<float>(20)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), -tile_size.height * static_cast<float>(20)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), -tile_size.height * static_cast<float>(20)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), -tile_size.height * static_cast<float>(20)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), -tile_size.height * static_cast<float>(20)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), -tile_size.height * static_cast<float>(20)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), -tile_size.height * static_cast<float>(20)));
	type_.push_back(14);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(20)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), -tile_size.height * static_cast<float>(20)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), -tile_size.height * static_cast<float>(18)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), -tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), -tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), -tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), -tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), -tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), -tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), -tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), -tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), -tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), -tile_size.height * static_cast<float>(16)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), -tile_size.height * static_cast<float>(16)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), -tile_size.height * static_cast<float>(16)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), -tile_size.height * static_cast<float>(16)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(16)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(18)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(20)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(22)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(24)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), -tile_size.height * static_cast<float>(24)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), -tile_size.height * static_cast<float>(26)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), -tile_size.height * static_cast<float>(26)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), -tile_size.height * static_cast<float>(26)));
	type_.push_back(16);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), -tile_size.height * static_cast<float>(26)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), -tile_size.height * static_cast<float>(26)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), -tile_size.height * static_cast<float>(26)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), -tile_size.height * static_cast<float>(26)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), -tile_size.height * static_cast<float>(26)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), -tile_size.height * static_cast<float>(26)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), -tile_size.height * static_cast<float>(26)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), -tile_size.height * static_cast<float>(28)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), -tile_size.height * static_cast<float>(30)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), -tile_size.height * static_cast<float>(32)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), -tile_size.height * static_cast<float>(32)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), -tile_size.height * static_cast<float>(32)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), -tile_size.height * static_cast<float>(32)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), -tile_size.height * static_cast<float>(32)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), -tile_size.height * static_cast<float>(32)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), -tile_size.height * static_cast<float>(32)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), -tile_size.height * static_cast<float>(32)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), -tile_size.height * static_cast<float>(32)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), -tile_size.height * static_cast<float>(32)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), -tile_size.height * static_cast<float>(34)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), -tile_size.height * static_cast<float>(36)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), -tile_size.height * static_cast<float>(38)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), -tile_size.height * static_cast<float>(38)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), -tile_size.height * static_cast<float>(38)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), -tile_size.height * static_cast<float>(38)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), -tile_size.height * static_cast<float>(38)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), -tile_size.height * static_cast<float>(38)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), -tile_size.height * static_cast<float>(38)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), -tile_size.height * static_cast<float>(40)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), -tile_size.height * static_cast<float>(40)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), -tile_size.height * static_cast<float>(42)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), -tile_size.height * static_cast<float>(44)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), -tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), -tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), -tile_size.height * static_cast<float>(46)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), -tile_size.height * static_cast<float>(46)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), -tile_size.height * static_cast<float>(46)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), -tile_size.height * static_cast<float>(46)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), -tile_size.height * static_cast<float>(46)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), -tile_size.height * static_cast<float>(46)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(46)));
	type_.push_back(16);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(48)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(50)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(52)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), -tile_size.height * static_cast<float>(52)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), -tile_size.height * static_cast<float>(52)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), -tile_size.height * static_cast<float>(52)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), -tile_size.height * static_cast<float>(52)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), -tile_size.height * static_cast<float>(52)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), -tile_size.height * static_cast<float>(52)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), -tile_size.height * static_cast<float>(52)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), -tile_size.height * static_cast<float>(52)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), -tile_size.height * static_cast<float>(52)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), -tile_size.height * static_cast<float>(52)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), -tile_size.height * static_cast<float>(52)));
	type_.push_back(11);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), -tile_size.height * static_cast<float>(52)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), -tile_size.height * static_cast<float>(54)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), -tile_size.height * static_cast<float>(56)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), -tile_size.height * static_cast<float>(58)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), -tile_size.height * static_cast<float>(58)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), -tile_size.height * static_cast<float>(58)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), -tile_size.height * static_cast<float>(58)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), -tile_size.height * static_cast<float>(58)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), -tile_size.height * static_cast<float>(58)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), -tile_size.height * static_cast<float>(58)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), -tile_size.height * static_cast<float>(58)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), -tile_size.height * static_cast<float>(60)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), -tile_size.height * static_cast<float>(62)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), -tile_size.height * static_cast<float>(64)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), -tile_size.height * static_cast<float>(66)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), -tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), -tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), -tile_size.height * static_cast<float>(68)));
	type_.push_back(12);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), -tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), -tile_size.height * static_cast<float>(68)));
	type_.push_back(11);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(68)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(70)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(72)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(74)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), -tile_size.height * static_cast<float>(74)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), -tile_size.height * static_cast<float>(74)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), -tile_size.height * static_cast<float>(76)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), -tile_size.height * static_cast<float>(78)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), -tile_size.height * static_cast<float>(80)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), -tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), -tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(82)));
	type_.push_back(15);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(84)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(10), -tile_size.height * static_cast<float>(86)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), -tile_size.height * static_cast<float>(86)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(12), -tile_size.height * static_cast<float>(88)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(14), -tile_size.height * static_cast<float>(88)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(16), -tile_size.height * static_cast<float>(88)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), -tile_size.height * static_cast<float>(88)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), -tile_size.height * static_cast<float>(88)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), -tile_size.height * static_cast<float>(88)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), -tile_size.height * static_cast<float>(88)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), -tile_size.height * static_cast<float>(88)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), -tile_size.height * static_cast<float>(88)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), -tile_size.height * static_cast<float>(88)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), -tile_size.height * static_cast<float>(88)));
	type_.push_back(1);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), -tile_size.height * static_cast<float>(86)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), -tile_size.height * static_cast<float>(84)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), -tile_size.height * static_cast<float>(82)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), -tile_size.height * static_cast<float>(82)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), -tile_size.height * static_cast<float>(82)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), -tile_size.height * static_cast<float>(82)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), -tile_size.height * static_cast<float>(82)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), -tile_size.height * static_cast<float>(82)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), -tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), -tile_size.height * static_cast<float>(82)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), -tile_size.height * static_cast<float>(80)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), -tile_size.height * static_cast<float>(78)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(18), -tile_size.height * static_cast<float>(76)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(20), -tile_size.height * static_cast<float>(76)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(22), -tile_size.height * static_cast<float>(76)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(24), -tile_size.height * static_cast<float>(76)));
	type_.push_back(4);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(26), -tile_size.height * static_cast<float>(76)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(28), -tile_size.height * static_cast<float>(76)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(30), -tile_size.height * static_cast<float>(76)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(32), -tile_size.height * static_cast<float>(76)));
	type_.push_back(3);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(34), -tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(36), -tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(38), -tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(40), -tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(42), -tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(44), -tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(46), -tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(48), -tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), -tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), -tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), -tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(56), -tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), -tile_size.height * static_cast<float>(76)));
	type_.push_back(10);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), -tile_size.height * static_cast<float>(76)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), -tile_size.height * static_cast<float>(78)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), -tile_size.height * static_cast<float>(80)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(60), -tile_size.height * static_cast<float>(82)));
	type_.push_back(2);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(58), -tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(56), -tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(54), -tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(52), -tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	pos_.push_back(Vec2(tile_size.width * static_cast<float>(50), -tile_size.height * static_cast<float>(82)));
	type_.push_back(0);
	for (int i = 0; i < pos_.size(); ++i)
	{
		pos_.at(i) += Vec2(0, tile_size.height * static_cast<float>(100));
	}
	return true;
}